### PR TITLE
Update statement.inc.php

### PR DESCRIPTION
**Pull request by aethelwulffe**
is_auth_portal() is conditionally created, but is used in statement.inc.php unconditionally.

### CODE REVIEW

**Comment by marcusbow** [comment]
Funny thing is an issue involving these code changes popped up today.  Seems to fix our issues.

**Comment by aethelwulffe** [comment]
What issues did it solve for you?  Apparently not the blank PDF thingie?

**Comment by marcusbow** [comment]
It was preventing the pdf from being created in the first place.  So, just loading a blank screen listed unknown when attempting to save the pdf.

**Comment by aethelwulffe** [comment]
sO, DID THIS FIX THE PDF ISSUE?

**Comment by marcusbow** [comment]
The pdf is empty, but before it wasn't even doing that, just loading an empty window title unknown.

**Pull request merged**
